def ClumpFinding(Genome, k, L,t):
    j = 0
    clump = set()
    while (j+L)<=len(Genome):
        substrate = {}
        w = Genome[j:j+L]
        f = 0
        while (f+k)<=len(w):
            sub = w[f:f+k]
            if sub not in substrate:
                substrate[sub] = 1
            else :
                substrate[sub]+=1
            f+=1
        j+=1
        clumpList = [key for key in substrate.keys() if substrate[key]>=t]
        for l in clumpList:
            clump.add(l)
    return len(clump)

#Main
Genome = 'TTTTTTCCGCACAGGTGGTTGGTTCAAGAGAAAGAAACAGAAACTGCTAGAAACTGCGCCGAGGACGCTGATCCATTCGGTTTCGCAGATAACTAAACAGCGTCGTCGGGGGAATTTAATGTACGTATCACGTTAATGTAACACCGAATACGGGTCGACCTCCGGGGGTGTCTTGTTACCGGCTCTGCACTAACTCCGTGCGCGTGTACATACATAGGCGGGTCTACTGTGACATGATGACAGGCTAACTGCTGTGCTAAGCTAACTGAACTGGGTTAGCGGTCCGCTGTTTTCGAAACGGCACCTTAGGCTAATTAGTAATGCGGGGGCGGATAGTAGGATAGTGCTACCTTCGAACATATCATAACGGCCCCTCCCCGACTCTATAGACTCCGCGATAGTGCCGGCCCGTTGACGACTCGGTTTCCCTACCTCCTACCTACACGGCCAACAACCGGTCGGTCGATCCCCGTAAGGGCCGCTGTCTCCACGCCCGGAGCAAATACAGCGAACTACCCCTAACAACATGTTATCTATTATTTTCGTCGTTTTTATTTTCGTCGGGACTGCTTCGTAAAAACTGAGCCGACGACCCCCTATAGAAGGTGTCGATCTTGTTGTAGAGGACAAACAAAAATAACAAACAAAAATATGTCAGTCGCCTTTCTGCCCGGATATTGTATACAGTCAGAGAAGTATGCTGTCAAAAATGATGAAATTTTATCGATCTAAGACAGAATGGCTACACGGCGGTATCTCATATCTCACAGTATCTCACAACCTTTGATATATCCTTTGATTGATTTTGATATAGACGAATTACTAGCTACAGCTAGCTACCGAGCTACCGCGGTGGGTCAGTGCCCACGCGACCCCGCATTATCCGTACGCCGAAATATCTATGTTCATTACCCTAATCGTCTTCTCTGGAAGATGTTGGCTCGGTTGGCTCGCTCTCCACTGCTCCAGGCCCTGAGGTTGGAGCTTTCTATCCGCCCTATCTTTGGAGGGCTCTAAACCTGCGGGGTCCTATTTTGAATCGCATGAGTGACCGCCGATACTTGCGCACACCCTGAGAGCAGTTTCATTAGCGTCAACTACGTGTCAGATGCTAGGAACTATCTACGGCTAATAACCCCAACGCGCCCCCAACGCAACGATGTGAAATACATCTGGTACTCGGATAGCCGTCTGAGTCGAGAAACTACAAACAACAAAAAATTTGGAATGGAAATCGTAGTGCAAACGTAGGGCATGGCATGGGCATGTAGGGCATTTCGGATCCTCGGGTTGGCTGCGATATGCAATTCGGTCCCTTCGACGACAGACGACGACGACGACGACACCGACACGCTGTGCAATACAAATAACGTGGTCCGTAGACTAGACATGGTTTCGACGGGACATTTTTATCCATATCCAGCAGCATCCAGCTATGCCGCTCTGGTCCGCCTGTACAGATAGTTATTATTCTATACAAAACGTCGATGTTTCATAATTCTACTTGGCACATTACAACTCGCCGAAAATCCTCAACACGCGCTAGCTGTCTTACTCGATACAGGTCGTGTCGCGTGCGTGTCGTGTCTCGGACAAACCGTTTATGTGCCATCGGATGAATCTCCGACAAATTTACGCACTCAGCCGAACGTCAGCTCTTCAGATCAGGCCTTCGGGCGCCGTACCAATGTAAGGGGTTAGACTTAGAGCGCGTCTCGGTGCCAGCGTTTCAAGCTTAAGGTCGACGATCTCGCTTACTCGCTTACTCGCTTACTCGCTTACTCGCTTACTCGCTTACTCGCTTACTCGCTTA'
k = 8
L = 25
t = 4
ClumpFinding(Genome,k , L, t)