nucs = {'A':0,'C':1,'G':2,'T':3}
def PatternToNumber(Pattern):
    index = 0
    power = []
    for i in range(len(Pattern)-1,-1,-1):
        power.append(i)
    for i in range(len(Pattern)):
        index += nucs[Pattern[i]]*(4**power[i])
    return index

def ComputingFrequencies(Text, k):
    frequencyArray = []
    for i in range(4**k):
        frequencyArray.append(0)
    for i in range(len(Text)-k+1):
        pattern = Text[i:i+k]
        j = PatternToNumber(pattern)
        frequencyArray[j] = frequencyArray[j]+1
    for i in range(len(frequencyArray)):
        print frequencyArray[i],

Text = 'CGCGGCTATCTCAGAGAAGACATAGGATCGAAGCACTCCGCACATCGGTAACATACTTAGATGGCGCGTGGCACGTACACCACCAATAGATACGATCAAAGCCATTTCTGTACACTCAAGTATGCTACCGGATCATTTGCGGCAAGACATAATTTGCTCCAGGTAAGGAGTTCACATGAGCATAAAGATCCCATAGCCTAGATCATTAAACATAGGTATGCTCTAACCACCTGTGGAGGGCATCCCCATATGTGCAATCGGCTTATGCGTTTAGCAAACCTTTAATAATACATCCCTTATGAGGCCGCTAAGGTCCAATGTCACGGCGGCACCCGACCTTTCGTAGATGCCGAAACGCGGTTCCTGCATCCCACCGATTGCCTGGTGTATAAGGTGGCTGACGGGGAATGATTCGTAAAAGTCCCCAAAAATCCATTGGGACTGTACCCCCTTCAGGACTCGGAGTCGACCGACGGTAATTGTACCCATGACGTGTTGAGAGTGTCAGACCCTTCACGACGTTTCGTCATCTGCCCACGTCCAGAAAGTTCGGACACATCGCGAAATGGTTGAATTGGACCATCTATCTTCTACCTCACTTATTGCCGCAC'
print ComputingFrequencies(Text,5)
