def FrequentWords(Text, k):
    count = {}
    FrequentPattern_raw = []
    FrequentPattern = []
    for i in range(len(Text)-k+1):
        Pattern = Text[i:i+k]
        count[Pattern] = PatternCount(Text, Pattern)
    maxCount = max(count.values())
    for i in range(len(Text)-k+1):
        if count[Text[i:i+k]] == maxCount:
            FrequentPattern_raw.append(Text[i:i+k])
    for i in FrequentPattern_raw:
        if i not in FrequentPattern:
            FrequentPattern.append(i)
    return FrequentPattern

def PatternCount(Text, Pattern):
    count = 0
    for i in range(len(Text)-len(Pattern)+1):
        if Text[i:i+len(Pattern)] == Pattern:
            count += 1
    return count

#Main
Text = 'AAGTTTCTGTAAGCTGTAAGCTCTTAACTGTAAGCTCTTAACTGAGTCCTGGAATACAAGTTTCTGAGTCCTGGAATACCTTAACTCTTAACTCTTAACTCTTAACTGAGTCCTCTTAACTGAGTCCTAAGTTTCTAAGTTTCTGGAATACGAGTCCTGTAAGCTGTAAGCTGTAAGCTCTTAACTGGAATACAAGTTTCTGTAAGCTCTTAACTGAGTCCTGTAAGCTAAGTTTCTGGAATACGTAAGCTCTTAACTGGAATACAAGTTTCTCTTAACTGTAAGCTGAGTCCTGTAAGCTCTTAACTAAGTTTCTCTTAACTGGAATACGTAAGCTGAGTCCTGGAATACAAGTTTCTAAGTTTCTGTAAGCTGGAATACAAGTTTCTCTTAACTAAGTTTCTCTTAACTGAGTCCTCTTAACTGTAAGCTGGAATACCTTAACTGGAATACGTAAGCTGTAAGCTGGAATACCTTAACTGAGTCCTGAGTCCTGAGTCCTGGAATACGTAAGCTCTTAACTAAGTTTCTGGAATACGTAAGCTGTAAGCTGTAAGCTAAGTTTCTGGAATACGGAATACGTAAGCTGGAATACGAGTCCTAAGTTTCTGGAATACGGAATACGAGTCCTAAGTTTCTCTTAACTGGAATACGTAAGCTCTTAACTAAGTTTCTGAGTCCTAAGTTTCTGTAAGCTGTAAGCTGTAAGCTAAGTTTCTGAGTCCTCTTAACTGAGTCCTGTAAGCTAAGTTTCTAAGTTTCTCTTAACTGGAATACGTAAGCTAAGTTTCTGTAAGCT'
K = 14
A = FrequentWords(Text,K)
for i in range(len(A)):
	print A[i],
